import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { createSynapseHost, registerSynapse } from '../workflows/synapse-host.mjs'
import { WorkspaceStore } from '../workflows/vendor/synapse/index.js'
import { isHumanUserEvent } from '../workflows/synapse-projection.mjs'

test('cold logs, incremental refresh, native branch, hide and restart stay in isolated metadata', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'deepviewer-map-test-'))
  const events = [{ type: 'user/message', seq: 0, time: 1, data: { content: [{ type: 'text', text: 'Synthetic question' }] } }]
  const logs = new Map([['parent', {session:{id:'parent',cwd:'/synthetic'}, inheritedEventCount:0, events}]])
  let reads = 0
  const query = { listSessions: async () => [...logs.values()].map(log => ({header:log.session})), readSession: async id => { reads++; if (!logs.has(id)) throw Error('missing'); return logs.get(id) } }
  const dataFile = join(dir,'map.json'), host = createSynapseHost({query,dataFile})
  const request = (path,method='GET',body) => host.call({path,method,body:body===undefined?undefined:JSON.stringify(body)})
  try {
    const list = await request('/synapse/api/workspaces')
    const path = '/synapse/api/workspaces/'+list.workspaces[0].id
    let graph = (await request(path)).workspace
    const parent = graph.threads[0]
    assert.equal(parent.messages[0].text,'Synthetic question')
    assert.equal(reads,1)
    await assert.rejects(request('/synapse/api/reset','POST'),/Unsupported/)
    await assert.rejects(host.call({path,body:'x'}))
    await assert.rejects(host.call({path,body:'x'.repeat(70000)}),/Invalid/)
    logs.set('child',{session:{id:'child',cwd:'/synthetic',parentSession:'parent'},inheritedEventCount:1,events:[...events,{type:'user/message',seq:1,time:2,data:{content:[{type:'text',text:'Synthetic branch'}]}}]})
    host.changed('child')
    graph = (await request(path)).workspace
    assert.equal(graph.threads.find(t=>t.dshSessionId==='child').parentId,parent.id)
    assert.equal(graph.threads.find(t=>t.dshSessionId==='child').messages.length,1)
    await assert.rejects(request('/synapse/api/threads/'+parent.id+'/branch','POST',{dshSessionId:'parent',title:'forged'}),/native session parent/)
    await request('/synapse/api/threads/'+parent.id,'DELETE')
    await host.dispose()
    assert.equal(logs.get('parent').events,events)
    const restored = createSynapseHost({query,dataFile})
    try {
      const list = await restored.call({path:'/synapse/api/workspaces'})
      for (const summary of list.workspaces) {
        const graph = (await restored.call({path:'/synapse/api/workspaces/'+summary.id})).workspace
        assert.equal(graph.threads.some(t=>t.dshSessionId==='parent'),false)
      }
    } finally { await restored.dispose() }
    assert.ok((await readFile(dataFile,'utf8')).includes('hiddenSessionIds'))
  } finally { await host.dispose(); await rm(dir,{recursive:true,force:true}) }
})
test('only the owned authenticated RPC route is registered, with no HTTP handler', async () => {
  let handler, disposed
  const owner = {connection:{rpc:{handle:(channel,fn,scope)=>{assert.equal(channel,'/deepviewer-synapse'); assert.equal(scope,owner); handler=fn}}}}
  const ctx = {inject:(_,fn)=>fn(owner),on:()=>{},effect:fn=>{disposed=fn()},sessionQuery:{}}
  registerSynapse(ctx)
  const response = await handler('reset',{})
  assert.equal(response.ok,false)
  await disposed()
})

function user(seq, text, source) {
  return { type: 'user/message', seq, time: seq + 1, surfaceOp: 'append', data: { content: [{ type: 'text', text }], ...(source === undefined ? {} : { source }) } }
}
function reply(seq, text, turn = 1) {
  return { type: 'assistant/message', seq, time: seq + 1, data: { turn, step: 1, message: { content: [{ type: 'text', text }] } } }
}

test('native source classification excludes injected context while preserving human quotations and legacy prompts', () => {
  const reminder = '<system-reminder>instructions</system-reminder>'
  assert.equal(isHumanUserEvent(user(0, reminder, { kind: 'agent-instructions' })), false)
  assert.equal(isHumanUserEvent(user(0, reminder, { kind: 'user' })), true)
  assert.equal(isHumanUserEvent(user(0, reminder)), false)
  assert.equal(isHumanUserEvent(user(0, 'Explain ' + reminder)), true)
  assert.equal(isHumanUserEvent(user(0, '[model changed: assistant turns above this point were generated by a; the session continues with b]')), false)
  assert.equal(isHumanUserEvent(user(0, '[model changed: assistant turns above this point were generated by a; the session continues with b]', { kind: 'user' })), true)
  assert.equal(isHumanUserEvent(user(0, 'The approval policy changed from "ask" to "never" (changed by the user).')), false)
  assert.equal(isHumanUserEvent(user(0, 'Ordinary old prompt')), true)
  assert.equal(isHumanUserEvent(user(0, 'unknown injected producer', { kind: 'new-plugin' })), false)
  assert.equal(isHumanUserEvent({ ...user(0, 'replacement snapshot', { kind: 'user' }), surfaceOp: { op: 'replace', start: 0, end: 2 } }), false)
})

test('rebuild Build 38 cards from native logs without losing graph identity, layout, notes, hidden sessions or branch cuts', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'deepviewer-map-rebuild-'))
  const dataFile = join(dir, 'map.json')
  const reminder = '<system-reminder>Workspace instructions</system-reminder>'
  const events = [
    user(0, '真实问题一', { kind: 'user' }),
    user(1, reminder, { kind: 'agent-instructions' }),
    user(2, '[model changed: assistant turns above this point were generated by old; the session continues with new]', { kind: 'model-selection' }),
    user(3, 'The approval policy changed from "ask" to "never" (changed by the user).', { kind: 'user-approval' }),
    reply(4, '真实回答一'),
    user(5, reminder, { kind: 'user' }),
    { type: 'tool/call', seq: 6, time: 7, data: { turn: 2, step: 1, callId: 'read', name: 'file/read', arguments: '{}' } },
    reply(7, '真实回答二', 2),
    { type: 'tool/result', seq: 8, time: 9, data: { turn: 2, step: 1, message: { source: { callId: 'read' }, content: [{ type: 'text', text: 'read content' }] } } },
    { type: 'turn/end', seq: 9, time: 10, data: { turn: 2, reason: { kind: 'error', error: { message: 'Expected failure' } } } },
  ]
  const childEvents = [...events.slice(0, 5), user(5, '分支真实问题', { kind: 'user' }), user(6, reminder, { kind: 'agent-instructions' }), reply(7, '分支真实回答')]
  const logs = new Map([
    ['child', { session: { id: 'child', cwd: '/synthetic', parentSession: 'parent' }, inheritedEventCount: 5, events: childEvents }],
    ['parent', { session: { id: 'parent', cwd: '/synthetic' }, inheritedEventCount: 0, events }],
    ['hidden', { session: { id: 'hidden', cwd: '/synthetic' }, inheritedEventCount: 0, events: [user(0, 'hidden prompt', { kind: 'user' })] }],
  ])
  const query = { listSessions: async () => [...logs.values()].map(log => ({ header: log.session })), readSession: async id => logs.get(id) }
  const serializedLogs = JSON.stringify([...logs])
  const legacy = new WorkspaceStore(dataFile)
  let parentId, childId, questionId, workspaceId
  try {
    // Seed the exact append-only projection from Build 38, including its bad cards.
    for (const log of logs.values()) await legacy.projectSession({ id: log.session.id, header: { ...log.session, seedLength: log.inheritedEventCount }, events: log.events }, log.inheritedEventCount)
    const graph = await legacy.get((await legacy.list())[0].id)
    const parent = graph.threads.find(thread => thread.dshSessionId === 'parent')
    const child = graph.threads.find(thread => thread.dshSessionId === 'child')
    const hidden = graph.threads.find(thread => thread.dshSessionId === 'hidden')
    parentId = parent.id; childId = child.id; workspaceId = graph.id; questionId = parent.messages.find(message => message.sourceSeq === 0).id
    assert.equal(parent.messages.filter(message => message.kind === 'user').length, 5)
    await legacy.updateThread(parent.id, { position: { x: 543, y: -120 } })
    await legacy.addMessage(parent.id, 'Existing unbound canvas note')
    await legacy.removeThread(hidden.id)
  } finally { clearTimeout(legacy.flushTimer); await legacy.flush(); await legacy.serial }

  const host = createSynapseHost({ query, dataFile })
  let restored
  try {
    const graph = (await host.call({ path: '/synapse/api/workspaces/' + workspaceId })).workspace
    const parent = graph.threads.find(thread => thread.dshSessionId === 'parent')
    const child = graph.threads.find(thread => thread.dshSessionId === 'child')
    assert.equal(parent.id, parentId)
    assert.deepEqual(parent.position, { x: 543, y: -120 })
    assert.equal(parent.messages.find(message => message.sourceSeq === 0).id, questionId)
    assert.deepEqual(parent.messages.filter(message => message.kind === 'user' && Number.isSafeInteger(message.sourceSeq)).map(message => message.sourceSeq), [0, 5])
    assert.deepEqual(parent.messages.filter(message => message.kind === 'assistant').map(message => message.text), ['真实回答一', '真实回答二'])
    assert.equal(parent.messages.find(message => message.kind === 'error').text, 'Expected failure')
    assert.equal(parent.messages.find(message => message.sourceSeq === 7).process[0].result, 'read content')
    assert.equal(parent.messages.at(-1).text, 'Existing unbound canvas note')
    assert.equal(child.id, childId)
    assert.equal(child.parentId, parentId)
    assert.equal(child.sourceSeedLength, 5)
    assert.deepEqual(child.messages.map(message => message.text), ['分支真实问题', '分支真实回答'])
    assert.equal(graph.threads.some(thread => thread.dshSessionId === 'hidden'), false)
    assert.equal(JSON.stringify([...logs]), serializedLogs)
    await host.dispose()
    restored = createSynapseHost({ query, dataFile })
    const replay = (await restored.call({ path: '/synapse/api/workspaces/' + workspaceId })).workspace
    assert.deepEqual(replay.threads.find(thread => thread.id === parentId).messages, parent.messages)
    assert.deepEqual(replay.threads.find(thread => thread.id === parentId).position, parent.position)
    assert.equal((await readFile(dataFile, 'utf8')).includes('"hidden"'), true)
  } finally { await host.dispose(); await restored?.dispose(); await rm(dir, { recursive: true, force: true }) }
})


test('attachment-only human prompts rebuild as independent turns, while empty content and injected attachments do not', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'deepviewer-map-attachments-'))
  const dataFile = join(dir, 'map.json')
  const attachmentPrompt = (seq, content, source = { kind: 'user' }) => ({ ...user(seq, '', source), data: { source, content } })
  const events = [
    user(0, 'Before attachments', { kind: 'user' }), reply(1, 'Before answer', 1),
    attachmentPrompt(2, [{ type: 'image', attachment: { name: 'PRIVATE_IMAGE_NAME', path: '/PRIVATE_IMAGE_PATH', attachmentId: 'PRIVATE_IMAGE_ID' } }]),
    { type: 'tool/call', seq: 3, time: 4, data: { turn: 2, step: 1, callId: 'inspect-image', name: 'image/read', arguments: '{}' } },
    reply(4, 'Image answer', 2),
    { type: 'tool/result', seq: 5, time: 6, data: { turn: 2, step: 1, message: { source: { callId: 'inspect-image' }, content: [{ type: 'text', text: 'Image inspected' }] } } },
    { type: 'turn/end', seq: 6, time: 7, data: { turn: 2, reason: { kind: 'error', error: { message: 'Image failure' } } } },
    attachmentPrompt(7, [{ type: 'text', text: '  ' }, { type: 'file', attachment: { name: 'PRIVATE_FILE_NAME', path: '/PRIVATE_FILE_PATH', attachmentId: 'PRIVATE_FILE_ID' } }]),
    reply(8, 'File answer', 3),
    { type: 'turn/end', seq: 9, time: 10, data: { turn: 3, reason: { kind: 'cancelled' } } },
    attachmentPrompt(10, []), attachmentPrompt(11, [{ type: 'text', text: '  ' }]),
    attachmentPrompt(12, [{ type: 'image', attachment: { name: 'injected-image' } }], { kind: 'agent-instructions' }),
  ]
  const log = { session: { id: 'attachment-session', cwd: '/synthetic' }, inheritedEventCount: 0, events }
  const query = { listSessions: async () => [{ header: log.session }], readSession: async () => log }
  const untouched = JSON.stringify(log)
  const legacy = new WorkspaceStore(dataFile)
  let workspaceId, threadId
  try {
    const original = await legacy.projectSession({ id: log.session.id, header: log.session, events })
    workspaceId = (await legacy.list())[0].id; threadId = original.id
    assert.deepEqual(original.messages.filter(message => message.kind === 'user').map(message => message.sourceSeq), [0])
    await legacy.updateThread(threadId, { position: { x: 200, y: 300 } })
  } finally { clearTimeout(legacy.flushTimer); await legacy.flush(); await legacy.serial }
  const host = createSynapseHost({ query, dataFile })
  let restarted
  try {
    const graph = (await host.call({ path: '/synapse/api/workspaces/' + workspaceId })).workspace
    const thread = graph.threads[0]
    assert.equal(thread.id, threadId)
    assert.deepEqual(thread.position, { x: 200, y: 300 })
    const users = thread.messages.filter(message => message.kind === 'user')
    assert.deepEqual(users.map(message => message.sourceSeq), [0, 2, 7])
    assert.deepEqual(users.slice(1).map(message => [message.text, message.deepviewerAttachmentOnly]), [['附件消息', true], ['附件消息', true]])
    const rounds = users.map((question, index) => ({
      question: question.sourceSeq,
      replies: thread.messages.filter(message => message.sourceSeq > question.sourceSeq && message.sourceSeq < (users[index + 1]?.sourceSeq ?? Infinity)),
    }))
    assert.deepEqual(rounds.map(round => round.replies.filter(message => message.kind === 'assistant').map(message => message.text)), [['Before answer'], ['Image answer'], ['File answer']])
    assert.equal(rounds[1].replies.find(message => message.kind === 'assistant').process[0].result, 'Image inspected')
    assert.equal(rounds[1].replies.find(message => message.kind === 'error').text, 'Image failure')
    assert.equal(rounds[2].replies.find(message => message.kind === 'error').text, '本轮已取消')
    assert.equal(JSON.stringify(thread.messages).includes('PRIVATE_'), false)
    assert.equal(JSON.stringify(log), untouched)
    await host.dispose()
    restarted = createSynapseHost({ query, dataFile })
    const replay = (await restarted.call({ path: '/synapse/api/workspaces/' + workspaceId })).workspace.threads[0]
    assert.deepEqual(replay.messages, thread.messages)
  } finally { await host.dispose(); await restarted?.dispose(); await rm(dir, { recursive: true, force: true }) }
})


test('an event appended during a pending projection is read on the next request before cache expiry', { timeout: 5000 }, async () => {
  const dir = await mkdtemp(join(tmpdir(), 'deepviewer-map-dirty-race-'))
  const started = Promise.withResolvers(), resume = Promise.withResolvers()
  const log = { session: { id: 'parent', cwd: '/synthetic' }, inheritedEventCount: 0, events: [user(0, 'First synthetic turn', { kind: 'user' })] }
  let reads = 0
  const query = {
    listSessions: async () => [{ header: log.session }],
    readSession: async () => {
      reads += 1
      const snapshot = structuredClone(log)
      if (reads === 1) { started.resolve(); await resume.promise }
      return snapshot
    },
  }
  const host = createSynapseHost({ query, dataFile: join(dir, 'map.json') })
  try {
    host.changed('parent')
    const first = host.call({ path: '/synapse/api/workspaces' })
    await started.promise
    const concurrent = host.call({ path: '/synapse/api/workspaces' })
    log.events.push(user(1, 'Appended during the old snapshot', { kind: 'user' }))
    host.changed('parent')
    const untouched = JSON.stringify(log)
    resume.resolve()
    const [initial, shared] = await Promise.all([first, concurrent])
    assert.equal(reads, 1, 'Concurrent requests should share the first projection')
    assert.deepEqual(shared, initial)
    const path = '/synapse/api/workspaces/' + initial.workspaces[0].id
    const refreshed = (await host.call({ path })).workspace.threads[0]
    assert.equal(reads, 2, 'Unconsumed events must bypass the fresh 1500ms cache')
    assert.deepEqual(refreshed.messages.filter(message => message.kind === 'user').map(message => message.sourceSeq), [0, 1])
    await host.call({ path })
    assert.equal(reads, 2, 'A fully consumed projection should resume caching')
    assert.equal(JSON.stringify(log), untouched)
  } finally { resume.resolve(); await host.dispose(); await rm(dir, { recursive: true, force: true }) }
})

test('a session created after the pending catalogue snapshot is projected on the next request', { timeout: 5000 }, async () => {
  const dir = await mkdtemp(join(tmpdir(), 'deepviewer-map-created-race-'))
  const started = Promise.withResolvers(), resume = Promise.withResolvers()
  const parentEvent = user(0, 'Synthetic parent turn', { kind: 'user' })
  const logs = new Map([['parent', { session: { id: 'parent', cwd: '/synthetic' }, inheritedEventCount: 0, events: [parentEvent] }]])
  const reads = new Map()
  const query = {
    listSessions: async () => [...logs.values()].map(log => ({ header: structuredClone(log.session) })),
    readSession: async id => {
      reads.set(id, (reads.get(id) ?? 0) + 1)
      const snapshot = structuredClone(logs.get(id))
      if (id === 'parent' && reads.get(id) === 1) { started.resolve(); await resume.promise }
      return snapshot
    },
  }
  const host = createSynapseHost({ query, dataFile: join(dir, 'map.json') })
  try {
    const pending = host.call({ path: '/synapse/api/workspaces' })
    await started.promise
    logs.set('child', { session: { id: 'child', cwd: '/synthetic', parentSession: 'parent' }, inheritedEventCount: 1,
      events: [parentEvent, user(1, 'Synthetic child first turn', { kind: 'user' })] })
    host.changed('child')
    const untouched = JSON.stringify([...logs])
    resume.resolve()
    const initial = await pending
    const graph = (await host.call({ path: '/synapse/api/workspaces/' + initial.workspaces[0].id })).workspace
    const parent = graph.threads.find(thread => thread.dshSessionId === 'parent')
    const child = graph.threads.find(thread => thread.dshSessionId === 'child')
    assert.ok(child, 'A new native session must not remain hidden by the catalogue cache')
    assert.equal(child.parentId, parent.id)
    assert.equal(child.sourceSeedLength, 1)
    assert.deepEqual(child.messages.filter(message => message.kind === 'user').map(message => message.sourceSeq), [1])
    assert.equal(reads.get('parent'), 1, 'Unchanged projected sessions should not be reread')
    assert.equal(reads.get('child'), 1)
    assert.equal(JSON.stringify([...logs]), untouched)
  } finally { resume.resolve(); await host.dispose(); await rm(dir, { recursive: true, force: true }) }
})
